### PR TITLE
Prescale settings now configurable

### PR DESCRIPTION
**Pull request by sharpner**
In order to provide better results smartcrop should allow the user which settings he wants.

this is especially necessary to solve #21  for me :P

### CODE REVIEW

**Comment by sharpner** [comment]
any blocker for merging this?

**Comment by muesli** [comment]
No blockers as I see it, just waiting for @michiwend to give his OK, too :-)

**Comment by sharpner** [comment]
good to know ;) thx

**Comment by sharpner** [comment]
bump^^

**Comment by sharpner** [comment]
I'll close this now.

**Pull request closed without merging**
