### PR TITLE
fix bug of opencv memory leak

### PR DESCRIPTION
**Pull request by chideat**
Two places used opencv but not release the memory.

### CODE REVIEW

**Comment by muesli** [comment]
Thanks for all the effort, it's really appreciated!

**Comment by muesli** [comment]
Sadly now the PR has multiple commits again. I'll review your changes, maybe we can just adjust the PR tile, though. Thanks again!

**Comment by chideat** [comment]
Sorry for multiple commits. As if the last commit is auto combined with last pull request. I'll try again.

**Comment by muesli** [comment]
If you push commits to the same branch, the pull request will get updated automatically. You need to use separate branches for separate pull requests.

**Comment by chideat** [comment]
Thanks, I've got it.

**Pull request closed without merging**
